### ISSUE TITLE
Guide about Group area disk usage

### ISSUE THREAD

**Issue by zengchang94622** [aistairc/abci-docs#199]
Hi, thanks for your nice work.

Now I am a user of ABCI server. I found there is only 200G disk space in home directory for each user. In order to run a large model on ABCI server, I have applied 5T group disk space. But I cannot find any guide about how to use Group disk in ABCI document.

Could you give me some advices about how to mount or use group disk?

**Comment by ahama** [comment]
Hi,

If your application has already been approved, please run "show_quota" command on an interactive node. You'll find your group directory path in the output. If this was not helpful, could you contact us via e-mail? https://docs.abci.ai/en/contact/

**Comment by zengchang94622** [comment]
> Hi,
> 
> If your application has already been approved, please run "show_quota" command on an interactive node. You'll find your group directory path in the output. If this was not helpful, could you contact us via e-mail? https://docs.abci.ai/en/contact/

Thanks for your reply.

It works! I will close this issue.
